language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
branches:
  only:
    - master
    - /\d+\.\d+\..+/
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq liblapack-dev libopenblas-dev graphviz
  - pip install numpy scipy lxml bs4 matplotlib coverage pydot trimesh
script: "MPLBACKEND=Agg nosetests -sv ."
notifications:
  recipients:
    - alexander.fabisch@dfki.de
  email:
    on_success: change
    on_failure: always
